### ISSUE TITLE
Inconsistent dependencies with python3.11

### ISSUE THREAD

**Issue by yoshson** [feinheit/fh-fablib#15]
Due to `fabric@2.6.0` depending on `invoke>=1.3,<2.0`
https://github.com/fabric/fabric/blob/52a73a6ab8d0a52fdd66abb1810d5650cc4aa8ac/setup.py#L70

and `invoke@1.7.3` using now removed deprecations,
https://github.com/pyinvoke/invoke/blob/9db5e88e2b49308636130e79bad0e9b6f36e93fa/invoke/tasks.py#L153

current fh-fablib seems to be incompatible with python3.11

**Comment by matthiask** [comment]
Fixed in a0b83fc85206eace78ecb69b421a49615776e3a0
