### ISSUE TITLE
Task für Tests

### ISSUE THREAD

**Issue by daenub** [feinheit/fh-fablib#8]
Hallo @matthiask,

Gibt es eine spezifischen Grund, warum es keinen vordefinierten Task gibt, welcher Tests ausführt?
Respektive, macht es mehr Sinn einen solchen Task lokal im Projekt zu definieren und aufzurufen?

**Comment by matthiask** [comment]
Als Teil von `fab check.deploy` wars mühsam (weil langsam), und ich habe mehr Freude daran, die Tests mit GitHub Actions ausführen zu lassen, zB als required checks für einen Merge.

Ich fahre hiermit: https://github.com/matthiask/workbench/blob/main/runtests.sh und hiermit: https://github.com/matthiask/workbench/blob/main/.github/workflows/python-app.yml sehr gut. Oder auch hiermit, noch mit Code Linting: https://github.com/feinheit/financemissionworld.com/blob/main/.github/workflows/python-app.yml

**Comment by matthiask** [comment]
... das sind aber alles nachgeschobene Gründe, der ursprüngliche Grund ist einfach: Ich habs beim Rewrite einfach (noch) nicht gemacht. Aber inzwischen finde ich, es ist besser so.

**Comment by daenub** [comment]
Ah super, merci für die Antwort :)
